# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 6 */2 * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: nico-zck
          template: classic
          config_timezone: Asia/Shanghai
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: ${{ secrets.AUTHOR_EMAILS }}

          # config_order: base.header, base.repositories, isocalendar, notable, topics

          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_types: commit, pull_request, issue

          plugin_topics: yes
          plugin_topics_mode: starred
          plugin_topics_limit: 15
          plugin_topics_sort: stars

          plugin_languages: yes
          plugin_languages_analysis_timeout: 25
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          # plugin_languages_recent_days: 14
          # plugin_languages_recent_load: 300
          # plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_languages_indepth: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_skipped: nico-zck/nico-zck
          plugin_languages_ignored: html, css
          plugin_languages_details: lines, percentage
          plugin_languages_recent_days: 180
          plugin_languages_recent_load: 600


          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
